// S&P 500 Companies (Top 135 by market cap and recognition)
export const exampleNames = [
  // Tech Giants
  'Apple',
  'Microsoft',
  'Amazon',
  'NVIDIA',
  'Alphabet',
  'Meta',
  'Tesla',
  'Broadcom',
  'Oracle',
  'Salesforce',
  'AMD',
  'Adobe',
  'Netflix',
  'Intel',
  'IBM',
  'Qualcomm',
  'Applied Materials',
  'ServiceNow',
  'Intuit',
  'Cisco',

  // Financial Services
  'Berkshire Hathaway',
  'JPMorgan Chase',
  'Visa',
  'Mastercard',
  'Bank of America',
  'Wells Fargo',
  'Goldman Sachs',
  'Morgan Stanley',
  'American Express',
  'PayPal',
  'BlackRock',
  'Charles Schwab',
  'S&P Global',
  'Citigroup',
  'U.S. Bancorp',
  'PNC Financial',
  'Truist',
  'Capital One',
  'State Street',
  'Discover',

  // Healthcare & Pharma
  'UnitedHealth Group',
  'Johnson & Johnson',
  'Eli Lilly and',
  'Pfizer',
  'AbbVie',
  'Merck',
  'Thermo Fisher Scientific',
  'Abbott',
  'Bristol-Myers Squibb',
  'Amgen',
  'Gilead Sciences',
  'CVS Health',
  'Cigna',
  'Anthem',
  'Moderna',
  'Regeneron Pharmaceuticals',
  'Vertex Pharmaceuticals',
  'Illumina',
  'Boston Scientific',
  'Medtronic',

  // Consumer Goods
  'Procter & Gamble',
  'Coca-Cola',
  'PepsiCo',
  'Walmart',
  'Home Depot',
  'Nike',
  "McDonald's",
  'Costco Wholesale',
  'Starbucks',
  'Target',
  "Lowe's Companies",
  'Colgate-Palmolive',
  'General Mills',
  'Mondelez International',
  'Kimberly-Clark',
  'Estée Lauder Companies',
  'Yum! Brands',
  'Chipotle Mexican Grill',
  'Dollar General',
  'Dollar Tree',

  // Industrial & Energy
  'Exxon Mobil',
  'Chevron',
  'ConocoPhillips',
  'Marathon Petroleum',
  'Valero Energy',
  'Phillips 66',
  'Boeing',
  'Lockheed Martin',
  'Raytheon',
  'General Electric',
  'Caterpillar',
  'Deere &',
  'Union Pacific',
  'United Parcel Service',
  'FedEx',
  'CSX',
  'Norfolk Southern',
  '3M',
  'Honeywell International',
  'General Dynamics',

  // Communications & Media
  'Walt Disney',
  'Comcast',
  'Verizon Communications',
  'AT&T',
  'T-Mobile US',
  'Charter Communications',
  'Warner Bros Discovery',
  'Paramount Global',
  'Fox',
  'News',

  // Other Notable Companies
  'Uber',
  'Airbnb',
  'DoorDash',
  'Block',
  'Spotify Technology',
  'Snap',
  'Pinterest',
  'Roku',
  'Peloton Interactive',
  'Zoom Video Communications',
  'Palantir',
  'Snowflake',
  'Datadog',
  'CrowdStrike',
  'Okta',
  'Twilio',
  'DocuSign',
  'Shopify',
  'Square',
  'Robinhood Markets',
  'Coinbase Global',
  'Unity Software',
  'Roblox',
  'DraftKings',
  'Penn Entertainment',
];
